Deleted a few more no-longer used scripts.
Heavily re-wrote mdcheck.  Uses cut rather than awk for efficiency;
now calls the checking pattern from inside the if-loop checking that
the file exists, eliminating the clunky 123 >/dev/null as a way of
breaking out of the loop.

Beginning to modify shell files so that they use sh rather than bash
where possible, and all adhere to a consistent style.

diff --git a/allowed b/allowed
--- a/allowed
+++ b/allowed
@@ -1,5 +1,7 @@
 #! /bin/sh
 
+# Check to see whether a word is in a given word list.
+
 WORDLIST=/usr/share/dict/words
 # this should be on most Unix systems. It is not, however, the
 # complete scrabble word list; if you have a better word list
@@ -8,18 +10,15 @@ SEARCH='grep -w'
 
 check ()
 {
-  # a neat trick from the Useless Use of Cat awards page.  we are
-  # running grep here for its exit code.  if there is a match it will
-  # return exit 0 and the if loop will succeed.  otherwise it will
-  # return exit 1 and the loop will fail.  redirection is to /dev/null
-  # so as not to pollute stdout.
-  if $SEARCH $1 $WORDLIST > /dev/null; then
-    echo "VALID"
-    $SEARCH $1 $WORDLIST
-    exit 0
-  fi
-  echo "INVALID"
-  exit 0
+    # a neat trick from the Useless Use of Cat awards page.  we are
+    # running grep here for its exit code.  if there is a match it will
+    # return exit 0 and the if loop will succeed.  otherwise it will
+    # return exit 1 and the loop will fail.  redirection is to /dev/null
+    # so as not to pollute stdout.
+    if $SEARCH $1 $WORDLIST > /dev/null; then
+        echo "VALID"
+    fi
+    echo "INVALID"
 }
 
 if [ $# -lt 1 ]; then
@@ -29,3 +28,5 @@ if [ $# -lt 1 ]; then
 fi
 
 check $1
+
+exit 0
diff --git a/fran b/fran
--- a/fran
+++ b/fran
@@ -1,11 +1,13 @@
 #! /bin/sh
-# frequency analysis tool
+
+# Frequency analyse a text file.
 
 TEMPFILE=$HOME/tmp
 
-if [ $# -lt 1 ]; then
-    echo "Use 'fran <filename>'."
-    exit
+if [ $# -ne 1 ]; then
+    echo "Error: wrong number of arguments"
+    echo "Syntax: `fran $filename`"
+    exit 1
 fi
 
 if [ $1 ]; then
@@ -20,3 +22,5 @@ fi
 sed 's/./&\n/g' $TEMPFILE | sort | uniq -c | sort -nr
 
 rm $TEMPFILE
+
+exit 0
diff --git a/mdcheck b/mdcheck
--- a/mdcheck
+++ b/mdcheck
@@ -1,34 +1,28 @@
 #!/bin/bash
-# from milo64 in the arch fora
-# checks if md5 of a file matches an md5 you give it
 
-if [ "$1" = "" ]; then
-  echo "ERR: Missing command-line parameter."
-  echo " "
-  echo "Syntax:"
-  echo "  mdcheck FILE ACTUAL-MD5"
-  exit 1
-fi
+# Check if a file's md5sum matches a string.
 
-if [ "$2" = "" ]; then
-  echo "ERR: Missing command-line parameter."
-  echo " "
-  echo "Syntax:"
-  echo "  mdcheck FILE ACTUAL-MD5"
-  exit 1
+# Usage: mdcheck $filename $md5string
+
+# Based on a script by milo64 from the Arch Fora.
+
+check () {
+    if [ "$(md5sum $1 | cut -d ' ' -f 1)" = "$2" ]; then
+        echo "Checksum matched."
+        exit 0
+    else
+        echo "Checksum not matched."
+        exit 1
+    fi
+}
+
+if [ $# -ne 2 ]; then
+    echo "ERROR: mdcheck requires two arguments."
 fi
 
 if [ -a "$1" ]; then
-  echo 123 > /dev/null
+    check $1 $2
 else
-  echo "ERR: '$1' No such file."
-  exit 1;
-fi
-
-if [ "$(md5sum $1 | awk '{print $1}')" = "$2" ]; then
-  echo "Checksum matched."
-  exit 0
-else
-  echo "Checksum not matched."
-  exit 1
+    echo "ERR: '$1' No such file."
+    exit 1;
 fi
