modified:   README.md 	new file:   mpdmenu 	modified:   rhythmenu 	new file:   sdfify 	new file:   sync

diff --git a/cosmo b/cosmo
--- a/cosmo
+++ b/cosmo
@@ -1,9 +1,11 @@
 #!/bin/bash
+# heavily rewritten 04-02-2014 to use getopts to handle command-line flags
+# still buggy and error prone: in particular, the -f and -i flags do not work properly
 
-tao=$HOME/documents/ToDo
+tao=$HOME/media/todo
 range=($(echo {1..100}))
 SUGGEST=0
-SEARCH='grep -w'
+SEARCH='grep'
 
 # shuffle function based on Knufth-Fisher-Yayes shuffle algorithm
 # http://mywiki.wooledge.org/BashFAQ/026 thank you!
@@ -23,63 +25,63 @@ shuffle() {
    done
 }
 
-# It Is No Longer This Simple
-#if [[ $# -gt 2 ]]; then
-   #echo "Too many arguments."
-   #echo "Use 'cosmo' for a random suggestion, or 'cosmo [1-100]' for a specific one."
-   #exit 1
-#fi
+# Valid options:
+# -a (all); -c (count) -h (usage options) -i (case insensitive) -f (word parts accepted) -s (search) -v (version)
+while getopts ac:fhis:v opt; do
+  case $opt in
+    a)
+      cat $tao
+      exit 0
+      ;;
+    i)
+      SEARCH='$SEARCH -i'
+      ;;
+    f)
+      SEARCH='$SEARCH -w'
+      ;;
+    c)
+      $SEARCH -c $OPTARG $tao
+      exit 0;
+      ;;
+    h)
+      echo "cosmo: bringing hilarious sex tips to your command line"
+      echo "Usage: cosmo [OPTION] [SEARCH TERM]"
+      echo "       cosmo [1-100]"
+      echo "       cosmo -a"
+      echo "       cosmo -h"
+      echo "cosmo returns a random sex suggestion taken from a list from the "
+      echo "Cosmopolitan UK website."
+      echo ""
+      echo "OPTIONS:"
+      echo "-s  returns a random suggestion containing the search term given."
+      echo "-a  returns all suggestions containing the search term given."
+      echo "-c  returns a count of how many suggestions contain a search term."
+      echo "-f  do not limit searches to exact matches."
+      echo "    cosmo is by default case-sensitive and matches only exact words."
+      echo "    Thus, 'cosmo the' will not return suggestions containing 'then' or 'there'."
+      echo "    'cosmo -f' turns this option off."
+      echo "-i  make matches case insensitive."
+      exit 0
+      ;;
+    s)
+      $SEARCH $OPTARG $tao
+      exit 0;
+      ;;
+    v)
+      echo "cosmo v.2.0"
+      exit 0
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG"
+      exit 1;
+      ;;
+    :)
+      echo "-$OPTARG requires an argument"
+  esac
+done
 
-# if no arguments, get a random number from the range.
 if [[ $# -eq 0 ]]; then
    shuffle range[@] && SUGGEST=${arr[1]}
-fi
-
-if [[ $3 == "--fuzzy" ]]; then
-  SEARCH='grep -i'
-fi
-
-if [[ $3 == "-i" ]]; then
-  SEARCH='grep -iw'
-fi
-
-if [[ $1 == "--search" ]]; then
-  $SEARCH $2 $tao | shuf -n 1
-  exit 0
-fi
-
-if [[ $1 == "--all" ]]; then
-  if [[ $# -gt 3 ]]; then
-    exit 1
-  fi
-  if [[ $# -gt 1 ]]; then
-    $SEARCH $2 $tao
-    exit 0
-  fi
-  less $tao
-fi
-
-if [[ $1 == "--count" ]]; then
-  SEARCH=$SEARCH'c'
-  if [[ $# -gt 1 ]]; then
-    $SEARCH $2 $tao
-    exit 0
-  fi
-  exit 1
-fi
-
-if [[ $1 == "--help" ]]; then
-  echo "Usage: cosmo [OPTION] [SEARCH TERM]"
-  echo "       cosmo [1-100]"
-  echo "cosmo returns a random sex suggestion taken from a list from the Cosmopolitan UK website."
-  echo ""
-  echo "OPTIONS:"
-  echo "--search     returns a random suggestion containing the search term given"
-  echo "--all        returns all suggestions containing the search term given"
-  echo "--count      returns a count of how many suggestions contain a search term"
-  echo "--fuzzy      do not limit searches to exact matches. cosmo's default functionality is case-sensitive and matches only exact words. Thus, 'cosmo the' will not return suggestions containing 'then' or 'there'. 'cosmo --fuzzy' turns this option off"
-  echo "-i           make matches case insensitive"
-  exit 0
 fi
 
 if [[ $# -eq 1 ]]; then
@@ -92,14 +94,5 @@ if [[ $# -eq 1 ]]; then
       exit 1
    fi
 fi
-
-# trying to test whether run from terminal. If not, send to notification daemon
-# currently doesn't work.
-if [ ! -t 0 ]; then
-  grep ^$SUGGEST: $tao | xargs notify-send
-  exit 0
-fi
-
-grep ^$SUGGEST: $tao
 
 exit 0
