Deleted more unused scripts.
Cosmetic changes to allowed and cloc.sh: adding colour.

Fixed misplaced else-statement in allowed: previously if a word was
valid both the valid and invalid code would run

Added error handling to cloc.sh

diff --git a/wallpaper b/wallpaper
--- a/wallpaper
+++ b/wallpaper
@@ -5,13 +5,17 @@
 DIR=$HOME/images/desktops
 SET="hsetroot -full"
 
-if [ $1 ]; then
-    if [ -d "$1" ]; then
-        DIR=$1
-    else
-        echo $1 "is not a directory"
-        echo "Continuing with ", $DIR
-    fi
+if [ $# -ne $1 ]; then
+    echo "ERROR: Wrong number of arguments."
+    echo "Usage: `wallpaper $directory`"
+    exit 1
+fi
+
+if [ -d "$1" ]; then
+    DIR=$1
+else
+    echo "WARNING: " $1 " is not a directory"
+    echo "Continuing with " $DIR
 fi
 
 find $DIR -type f -print | shuf -n 1 | xargs $SET
diff --git a/wordcount b/wordcount
--- a/wordcount
+++ b/wordcount
@@ -10,25 +10,32 @@ if [ $# -lt 1 ]; then
     exit 1
 fi
 
-if [ $1 ]; then
-    if [ ! -f "$1" ]; then
-        echo "Error: `$1` does not exist."
-        exit 1
-    else
-        FILENAME="$1"
-    fi
+if [ ! -f "$1" ]; then
+    echo "Error: `$1` does not exist."
+    exit 1
 fi
 
-cat $FILENAME > $TEMPFILE
+countwords () {
+    cat $1 > $TEMPFILE
 
-sed '
+    echo $1:
+
+    sed '
 # replace every character except for those in the set [A-Za-z0-9 ]
 # with nothing.
 s/[^a-zA-Z0-9 ]//g
 # replace every space with a new line
 s/\ /\n/g' $TEMPFILE \
-    | tr '[:upper:]' '[:lower:]' | sort | uniq -c | grep "[a-z]" - | sort -nr |  head -n 20
+        | tr '[:upper:]' '[:lower:]' | sort | uniq -c | grep "[a-z]" - | sort -nr |  head -n 20
 
-rm $TEMPFILE
+    echo ""
+
+    rm $TEMPFILE
+}
+
+for file in "$@"
+do
+    countwords $file
+done
 
 exit 0
