Deleted:
* touchoff was the same script as touchpad_toggle under a less
  descriptive name

* updown, sync, unsync, and dmenu_path are no longer used in any way

Modified:

* readme brought somewhat up to date

* More standardisation of style in bash and sh scripts

New:

* colours.sh

diff --git a/wordcount b/wordcount
--- a/wordcount
+++ b/wordcount
@@ -1,22 +1,34 @@
-#!/bin/bash
-# wordcounter
+#!/bin/sh
+
+# Return the 20 most-used words in a text file, and their number of uses.
 
 TEMPFILE=$HOME/tempfile
 
 if [ $# -lt 1 ]; then
-    echo "Use 'wordcount <filename>'."
-    exit
+    echo "Error: Not enough arguments."
+    echo "Syntax: `wordcount $filename`"
+    exit 1
 fi
+
 if [ $1 ]; then
     if [ ! -f "$1" ]; then
-        echo "Filename does not exist."
-        exit
+        echo "Error: `$1` does not exist."
+        exit 1
     else
         FILENAME="$1"
     fi
 fi
 
 cat $FILENAME > $TEMPFILE
-sed 's/\.//g;s/\(.*\)/\L\1/;s/\ /\n/g' $TEMPFILE | sort | uniq -c | sort -nr | head -n 20
+
+sed '
+# replace every character except for those in the set [A-Za-z0-9 ]
+# with nothing.
+s/[^a-zA-Z0-9 ]//g
+# replace every space with a new line
+s/\ /\n/g' $TEMPFILE \
+    | tr '[:upper:]' '[:lower:]' | sort | uniq -c | grep "[a-z]" - | sort -nr |  head -n 20
 
 rm $TEMPFILE
+
+exit 0
